routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/clients', 'ClientsController');

Route::get('monCV', function () {
    return view('monCV');
});

app/Clients.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clients extends Model
{
    protected $guarded = [];

    public function entreprise()
    {
        return $this->belongsTo('App\Entreprise');
    }

    public function getStatutAttribute($attributes)
    {
        return [
            '0'=>'Inactif',
            '1'=>'Actif',
            '2'=>'En attente'
        ][$attributes];
    }
}

app/Entreprise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entreprise extends Model
{
    protected $guarded = [];

    public function clients()
    {
        return $this->hasMany('App\Clients');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Clients;
use App\Entreprise;
use Illuminate\Http\Request;

class ClientsController extends Controller
{
    public function index()
    {
        $clients = Clients::with('entreprise')->paginate(5);
        $nombreClient = Clients::count();
        return view(
            'clients.index',
            compact(
                'clients',
                'nombreClient'
            )
        );
    }

    public function store()
    {
        $dataClient = request()->validate([
            'nom'=>'required',
            'email'=>'required|email',
            'statut'=>'required|integer',
            'entreprise_id'=>'required|integer'
        ]);

        Clients::create($dataClient);

        return back();
    }

    public function create()
    {
        $entreprises =Entreprise::all();
        $client = new Clients();
        return view('clients.create', compact('entreprises', 'client'));
    }

    public function show($id)
    {
        return view('clients.show', ['client' => Clients::findOrFail($id)]);
    }

    public function edit(Clients $client)
    {
        # code...
        $entreprises = Entreprise::all();
        return view(
            'clients.edit',
            compact(
                'client',
                'entreprises'
            )
        );
    }

    public function update(Clients $client)
    {
        $dataClient = request()->validate([
            'nom'=>'required',
            'email'=>'required|email',
            'statut'=>'required|integer',
            'entreprise_id'=>'required|integer'
        ]);

        $client->update($dataClient);

        return redirect('clients/'.$client->id);
    }

    public function destroy(Clients $client)
    {
        $client->delete();

        return redirect('/clients');
    }

    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('title')
    {{ "Ajout d'un Client" }}
@endsection

@section('content')
    <div class="col-md-7 col-form-label text-md-right">
        <h1>{{ "Ajout d'un Client :"}}</h1>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('clients.store') }}">
            @include('layouts.form')

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4.5">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Enregistrer Les Informations') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('title')
    {{ "Edition du profil." }}
@endsection

@section('content')
    <div class="col-md-7 col-form-label text-md-right">
        <h1>{{ "Editer le profil de $client->nom"}}</h1>
    </div>

    <div class="card-body">
        <form method="POST" action="/clients/{{ $client->id }}">

            @method('PATCH')

            @include('layouts.form')

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Sauvegarder Les Informations') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('title')
    {{ "Clients" }}
@endsection

@section('content')
    <h1 >{{ "Nos Clients "}}
        <span class="badge badge-success badge-pill" >
            {{ $nombreClient }}
        </span>
    </h1>

    <div class="form-group">
        <a href="{{ route('clients.create') }}" type="submit" class="btn btn-primary my-3"
        name="nouveauClient" id="btn">{{ "Nouveau Client" }}</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">{{ "Nom" }}</th>
            <th scope="col">{{ "Entreprise" }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clients as $client)
                <tr>
                    <td><a href="{{ route('clients.show', ['client'=>$client->id]) }}">{{ $client->nom }}</a></td>
                    <td>{{ $client->entreprise->nomEntreprise }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
<br>
<div class="row d-flex justify-content-center">
    {{ $clients->links() }}
</div>

@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('title')
    {{ "Profil CLient" }}
@endsection


@section('content')
    <h1>{{ $client->nom }}</h1>

    <hr>

    <a href="{{ route('clients.edit', ['client'=> $client->id] )}}" class="btn btn-secondary my-3">{{ "Editer" }}</a>

    <form action="{{ route('clients.destroy', ['client'=>$client->id]) }}" method="POST" style="display :inline">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger" type="submit">{{ "Supprimer" }}</button>
    </form>
    <p>
        <strong>
            {{ "E-mail : " }}
        </strong>
        {{ $client->email }}
    </p>

    <p>
        <strong>
            {{ "Entreprise : " }}
        </strong>
        {{ $client->entreprise->nomEntreprise }}
    </p>
    <p>
        <strong>
            {{ "Statut : " }}
        </strong>
        {{ $client->statut }}
    </p>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="/">{{ "Tableau de Bord" }}</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ "Vous etes Connecté.!" }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        <meta charset="utf-8">

      {{--    <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  --}}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous">
        <title>App - @yield('title')</title>
        @yield('styleCSS')
    </head>

    <body>
        <div id="app">

            @include('layouts.navbar')

            <main class="py-4 container">
                @yield('content')
            </main>
        </div>
    </body>

    <footer class="text-right">
        <?print "jiji.dev &copy 2018-".date('Y');?>
    </footer>

</html>

resources/views/layouts/app2.blade.php
<!DOCTYPE html>
<html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
         integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
         crossorigin="anonymous">
        <title>App - @yield('title')</title>
        @yield('styleCSS')
    </head>

    <body>

        {{-- La ligne cidessous permet d'executer une partie du script qui
        se touve dans un autre fichier --}}

        @include('layouts.navbar')


        @yield('content')



    </body>
    <footer>
        <?print "jiji.dev &copy 2018-".date('Y');?>
    </footer>

</html>

{{-- En gros cette page est le squellette de toutes mes autres pages... --}}

resources/views/layouts/form.blade.php
@csrf

<div class="form-goup row">
    <div class="col col-lg-6 col-sm-12">
        <input id="nom" type="text" class="form-control @error('nom') is-invalid @enderror"
           name="nom" value="{{ old('nom') ?? $client->nom}}" placeholder="Nom du Client" required autocomplete="nom" autofocus>

            @error('nom')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
        @enderror
    </div>

    <div class="col col-lg-6 col-sm-12">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
            name="email" placeholder="E-mail" value="{{ old('email') ?? $client->email     }}" required autocomplete="email">

        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>

</div>
<br>
<div class="form-group row">
    <div class="col">
        <select class="custom-select @error('statut') is-invalid @enderror" name="statut" >
            <option value="0">{{ "Inactif" }}</option>
            <option value="1">{{ "Actif" }}</option>
            <option value="2">{{ "En Attente" }}</option>
        </select>
        @error('statut')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>

    <div class="col">
        <select class="custom-select @error('entreprise_id') is-invalid @enderror"
        name="entreprise_id" >
            @foreach ($entreprises as $entreprise)
                <option value="{{ $entreprise->id }}">{{ $entreprise->nomEntreprise }}</option>
            @endforeach
        </select>
        @error('entreprise_id')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

resources/views/layouts/navbar.blade.php
<div class="container" style="padding: 20px; border:1px solid red">

    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="/">{{ "Demo" }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="#">{{ "Menu 1 "}}<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/monCV    ">{{ "Mon CV" }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('clients.index') }}">{{ "voir nos Clients" }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
                {{ "Désactivé" }}
            </a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __("Se Connecter") }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __("S'inscrire") }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                            {{ __('Se déconnecter') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
    </nav>

</div>